Add native executable jfr demo
graalvm/graalvm-demos pull request #154
Opened 2022-11-25 20:06 UTC by LesiaChaban

2022-11-28 09:33 UTC, bhoran commented on native-jfr-demo/README.md
> +This example demonstrates how JDK Flight Recorder (JFR) as a tool for collecting diagnostic and profiling data running Java application, built into a JVM.
```suggestion
This example demonstrates how to use the JDK Flight Recorder (JFR) as a tool to collect diagnostic and profiling data in a running Java application, built into a JVM. 
```

2022-11-28 09:33 UTC, bhoran commented on native-jfr-demo/README.md
> +GraalVM Native Image supports JFR events and users can use [`jdk.jfr.Event`](https://docs.oracle.com/en/java/javase/11/docs/api/jdk.jfr/jdk/jfr/Event.html) API with a similar experience to using JFR
```suggestion
GraalVM Native Image supports JFR events and users can use the [`jdk.jfr.Event`](https://docs.oracle.com/en/java/javase/11/docs/api/jdk.jfr/jdk/jfr/Event.html) API with a similar experience to using JFR in the Java HotSpot VM.
```

2022-11-28 09:34 UTC, bhoran commented on native-jfr-demo/README.md
> +To record JFR events when running a native executable, JFR support and JFR recording must be enabled, and this guide covers how to do that.
```suggestion
To record JFR events when running a native executable, enable JFR support and JFR recording as described in this guide.
```

2022-11-28 09:36 UTC, bhoran commented on native-jfr-demo/README.md
> +> Note: JFR events recording is not supported on GraalVM JDK for Windows. JFR is only supported with native executables built on GraalVM JDK 11.
```suggestion
> Note: JFR event recording is not supported on GraalVM JDK for Windows. JFR is only supported with native executables built on GraalVM JDK 11.
```
I'm not sure I understand what this means.
Is JFR with GraalVM JDK11 supported on Windows?

2022-11-28 09:37 UTC, bhoran commented on native-jfr-demo/README.md
> +1. [Download GraalVM](https://www.graalvm.org/downloads/), unzip the archive, set the GraalVM home directory as the `$JAVA_HOME` environment variable and add `$JAVA_HOME/bin` to the `PATH` environmen
```suggestion
1. [Download GraalVM](https://www.graalvm.org/downloads/), unzip the archive, set the `$JAVA_HOME` environment variable as your GraalVM home directory  and add `$JAVA_HOME/bin` to your `PATH` environment variable.
```

2022-11-28 09:38 UTC, bhoran commented on native-jfr-demo/README.md
> +
Neither of these might be true. For example, I would expect many users to install GraalVM in a non-user location.

2022-11-28 09:39 UTC, bhoran commented on native-jfr-demo/README.md
> +1. Change directory to the demo subdirectories: _native-jfr-demo_:
```suggestion
1. Change directory to the demo subdirectory: _native-jfr-demo_:
```

2022-11-28 09:39 UTC, bhoran commented on native-jfr-demo/README.md
> +2. Compile the Java file on GraalVM JDK:
```suggestion
2. Compile the Java file using the GraalVM JDK:
```

2022-11-28 09:40 UTC, bhoran commented on native-jfr-demo/README.md
> +3. Build a native executable with the VM inspection enabled:
```suggestion
3. Build a native executable with VM inspection enabled:
```

2022-11-28 09:40 UTC, bhoran commented on native-jfr-demo/README.md
> +    It runs the application as a native executable. The `-XX:StartFlightRecording` option enables the built-in Flight Recorder and starts recording to a specified binary file, _recording.jfr_.
```suggestion
    This command runs the application as a native executable. The `-XX:StartFlightRecording` option enables the built-in Flight Recorder and starts recording to a specified binary file, _recording.jfr_.
```

2022-11-28 10:55 UTC, bhoran commented on native-jfr-demo/README.md
> +
I don't think these lines (14-22) are required. We can assume the reader understands the instructions without further details.

2022-11-28 10:56 UTC, bhoran commented on native-jfr-demo/README.md
> +3. Download or clone the demos repository:
```suggestion
3. Download the demos repository or clone it as follows:
```

2022-11-28 10:57 UTC, bhoran commented on native-jfr-demo/README.md
> +    It prints all events recorded by Flight Recorder.
```suggestion
    It prints all the events recorded by Flight Recorder.
```

2022-11-28 19:56 UTC, olyagpl commented
Approved.

2022-12-01 12:00 UTC, fniephaus requested changes

2022-12-01 12:00 UTC, fniephaus commented on native-jfr-demo/README.md
> +This example demonstrates how to use the JDK Flight Recorder (JFR) as a tool to collect diagnostic and profiling data in a running Java application, built into a JVM.
This example shows how to create a custom JFR event and use that in a native executable. Maybe we could start this guide with an example that shows what standard JFR events are emitted by, for example, `jwebserver`? What do you think?

2022-12-01 12:55 UTC, LesiaChaban commented on .github/workflows/native-jfr-demo.yml
> +          ./jfrdemo -XX:+FlightRecorder -XX:StartFlightRecording="filename=recording.jfr"
So, I need change this command to `./jfrdemo -XX:StartFlightRecording="filename=recording.jfr"`?

2022-12-01 13:01 UTC, fniephaus commented on .github/workflows/native-jfr-demo.yml
> +          ./jfrdemo -XX:+FlightRecorder -XX:StartFlightRecording="filename=recording.jfr"
It doesn't hurt but I'd probably remove it, yes.

2022-12-05 12:49 UTC, fniephaus approved these changes
LGTM. Please resolve the new conversations before merging. Thanks!

2022-12-05 12:49 UTC, fniephaus commented on native-jfr-demo/README.md
> +JFR is a tool to collect diagnostic and profiling data in a running Java application, built into a JVM.
```suggestion
This demo shows how to create a custom JDK Flight Recorder (JFR) event and use it in a native executable.
JFR is a tool to collect diagnostic and profiling data in a running Java application, and built into the JVM. 
```

2022-12-05 12:49 UTC, fniephaus commented on native-jfr-demo/README.md
> +GraalVM Native Image supports JFR events and users can use the [`jdk.jfr.Event`](https://docs.oracle.com/en/java/javase/11/docs/api/jdk.jfr/jdk/jfr/Event.html) API with a similar experience to using
We no longer support JDK11:
```suggestion
GraalVM Native Image supports JFR events and users can use the [`jdk.jfr.Event`](https://docs.oracle.com/en/java/javase/17/docs/api/jdk.jfr/jdk/jfr/Event.html) API with a similar experience to using JFR in the JVM. For example, to emit standard JFR events for the `jwebserver` application, you would run:
```

2022-12-05 12:49 UTC, fniephaus commented on native-jfr-demo/README.md
> +    ./jfrdemo -XX:StartFlightRecording="filename=recording.jfr"
You left `-XX:+FlightRecorder` in the `jwebserver` example, so let's use it consistently (it's not needed but also doesn't harm):
```suggestion
    ./jfrdemo -XX:+FlightRecorder -XX:StartFlightRecording="filename=recording.jfr"
```

2022-12-05 12:49 UTC, fniephaus commented on native-jfr-demo/README.md
> +    This command runs the application as a native executable. The `-XX:StartFlightRecording` option enables the built-in Flight Recorder and starts recording to a specified binary file, _recording.jf
```suggestion
    This command runs the application as a native executable. The `-XX:+FlightRecorder` and `-XX:StartFlightRecording` options enable the built-in Flight Recorder and start recording to a specified binary file, _recording.jfr_.
```

2022-12-05 13:20 UTC, merged