Add Native Image Demo how to Build a Native Shared Library
graalvm/graalvm-demos pull request #165
Opened 2022-12-12 12:23 UTC by LesiaChaban

The demo originates https://www.graalvm.org/latest/reference-manual/native-image/guides/build-native-shared-library/.

2022-12-12 13:13 UTC, fniephaus approved these changes
LGTM. Please address my comments before merging, thanks!

2022-12-12 13:13 UTC, fniephaus commented on .github/workflows/native-shared-library.yml
> +          components: 'native-image'
```suggestion
          components: 'native-image,llvm-toolchain'
```

and remove ` gu install llvm-toolchain` below.

2022-12-12 13:13 UTC, fniephaus commented on native-shared-library/README
> +#  Build a Native Shared Library
Share libraries are always native, so this is probably better:

```suggestion
# Build a Shared Library with Native Image
```

2022-12-12 13:13 UTC, fniephaus commented on native-shared-library/README
> +This examples demonstrates how to use the **Native Image C API**. You will:
```suggestion
This example demonstrates how to use the **Native Image C API**. We will:
```

2022-12-12 13:13 UTC, fniephaus commented on native-shared-library/README
> +    /demo/libenvmap.build_artifacts.txt
Remove this file:
```suggestion
    /demo/libenvmap.build_artifacts.txt
```

2022-12-12 13:13 UTC, fniephaus commented on native-shared-library/README
> +    native-image -jar <jarfile> --shared
This seems confusing, just remove it?
```suggestion
```

2022-12-12 13:13 UTC, fniephaus commented on native-shared-library/README
> +5. Run the C application by passing a string as an argument. For example:
```suggestion
5. And finally, run the C application by passing a string as an argument. For example:
```

2022-12-13 11:36 UTC, olyagpl requested changes

2022-12-13 11:36 UTC, olyagpl commented on native-shared-library/README
> +# Build a Shared Library with Native Image
# Build a Native Shared Library with GraalVM Native Image

2022-12-13 11:36 UTC, olyagpl commented on native-shared-library/README
> +This demo shows how to create a small Java class library, use `native-image` to create a native shared library, and then create a small C application that uses that shared library.
@LesiaChaban, please move all content from the website guide https://www.graalvm.org/dev/reference-manual/native-image/guides/build-native-shared-library/. Add missing pieces in the introduction part.

2022-12-13 12:50 UTC, olyagpl commented on README.md
> +      <td align="left" width="30%"><a href="/native-shared-library/">native-shared-library</a><br><a href="https://github.com/graalvm/graalvm-demos/actions/ni-shared-lib/.github/workflows/native-shar
https://github.com/graalvm/graalvm-demos/actions/ni-shared-lib/.github/workflows/native-shared-library.yml is not correct.

2022-12-13 13:08 UTC, olyagpl approved these changes

2022-12-13 13:09 UTC, merged