Upadate fortune-demo README and yml files.
graalvm/graalvm-demos pull request #213
Opened 2023-11-29 12:44 UTC by LesiaChaban

2023-11-29 16:02 UTC, bhoran commented on fortune-demo/README.md
> +1. Download and install the latest GraalVM JDK using the [SDKMAN!](https://sdkman.io/).
```suggestion
1. Download and install the latest GraalVM JDK using [SDKMAN!](https://sdkman.io/).
```

2023-11-29 16:02 UTC, bhoran requested changes
See suggestion

2023-12-05 09:44 UTC, LesiaChaban commented on fortune-demo/README.md
> +1. Download and install the latest GraalVM JDK using the [SDKMAN!](https://sdkman.io/).
I have applied your suggestion

2023-12-05 09:53 UTC, bhoran approved these changes

2023-12-07 14:27 UTC, olyagpl approved these changes

2023-12-07 14:28 UTC, merged