Pyfiglet GUI
graalvm/graalvm-demos pull request #254
Opened 2024-02-07 17:05 UTC by bhoran

A Small demo of accessing a Python class from Java.
1. Installs the pyfiglet module
2. Creates a Python class that acts as a wrapper for the pyfiglet module
3. Creates a Java interface that acts as a proxy for the wrapper
4. Creates a Swing JFrame to preview the pyfiglet _format_ method

From discussion with @timfel , this may be the wrong approach, and I'm not at all sure about the _pom.xml_ file.
All suggestions gratefully received (and please ignore the README for the time being)
![Pyfiglet GUI](https://github.com/graalvm/graalvm-demos/assets/12658122/7190b61b-c91e-40a5-b352-d8ab290667a4)

2024-02-14 14:06 UTC, timfel requested changes
This is a nice demo :)

2024-02-14 14:06 UTC, timfel commented on graalpy-install-package/src/main/java/com/oracle/example/graalpy/Main.java
> +    // is typechecking at this point, even at runtime. The reason is that Python
```suggestion
    // is no typechecking at this point, even at runtime. The reason is that Python
```

2024-02-14 14:06 UTC, timfel commented on graalpy-install-package/src/main/java/com/oracle/example/graalpy/Main.java
> +    // Getting the Python PyfigletWrapper class is an example of how data can be
The linebreaks are formatted strangely

2024-02-19 11:56 UTC, olyagpl approved these changes

2024-02-19 11:56 UTC, olyagpl commented on graalpy-install-package/README.md
> +4. Create a Swing JFrame ([PyfigletFrame.java](src/main/java/com/oracle/example/graalpy/PyfigletFrame.java)) that calls the proxy's _format_ method.
the proxy's `format` method.

2024-02-19 11:56 UTC, olyagpl commented on graalpy-install-package/README.md
> +2. Create a Python class ([PyfigletWrapper.py](src/main/resources/PyfigletWrapper.py)) that acts as a wrapper for the pyfiglet module.
the pyfiglet module >  the Pyfiglet module.

2024-02-19 11:56 UTC, olyagpl commented on graalpy-install-package/README.md
> +
Double space

2024-02-20 12:33 UTC, merged