Upgrade Fortune teller application to GraalVM for JDK 23
graalvm/graalvm-demos pull request #268
Opened 2024-06-28 12:20 UTC by olyagpl

Upgrade Fortune teller application to the latest Native Build tools and the latest features shipped with GraalVM for JDK 23.

2024-06-28 14:16 UTC, bhoran commented on fortune-demo/README.md
> +1. Download and install GraalVM using [SDKMAN!](https://sdkman.io/).
Need to provide the link to the graalvm downloads for Windows users.

2024-07-10 10:35 UTC, bhoran requested changes

2024-07-10 10:35 UTC, bhoran commented on README.md
> +      <td align="left" width="70%">A fortune teller Unix program. Build native executables using Gradle or Maven Native Image plugins.<br><strong>Technologies: </strong>Native Image, Native Build Too
```suggestion
      <td align="left" width="70%">A fortune teller Unix program. Build a native executable using Gradle or Maven Native Image plugins.<br><strong>Technologies: </strong>Native Image, Native Build Tools Maven plugin <br><strong>Reference: </strong><a href="https://graalvm.github.io/native-build-tools/latest/maven-plugin-quickstart.html">Getting Started with Maven Plugin for GraalVM Native Image</a></td>
```
If this shows how to use Gradle, it should probably have a link to the Gradle plugin.

2024-07-10 10:35 UTC, bhoran commented on fortune-demo/README.md
> +1. Download and install GraalVM. The easiest way is with [SDKMAN!](https://sdkman.io/jdks#graal):
```suggestion
1. Download and install GraalVM. The easiest way for Linux/macOS is with [SDKMAN!](https://sdkman.io/jdks#graal):
```

2024-07-10 10:35 UTC, bhoran commented on fortune-demo/README.md
>  2. Download or clone GraalVM demos repository:
```suggestion
2. Download or clone the GraalVM demos repository:
```

2024-07-10 10:35 UTC, bhoran commented on fortune-demo/README.md
> +    The command compiles the project, creates a JAR file with all dependencies, and then generates a native executable, `fortune`, in the _target_ directory, ready for use.
```suggestion
    The command compiles the project, creates a JAR file with all dependencies, and then generates a native executable, `fortune`, in the _target/_ directory, ready for use.
```

2024-07-10 10:35 UTC, bhoran commented on fortune-demo/README.md
>  1. Change to the _fortune-demo/fortune-gradle_ directory:
```suggestion
1. Change to the _fortune-demo/fortune-gradle/_ directory:
```

2024-07-10 10:35 UTC, bhoran commented on fortune-demo/README.md
>      When the command completes, a native executable, `fortune`, is generated in the _build/native/nativeCompile_ directory of the project and ready for use.
```suggestion
    When the command completes, a native executable, `fortune`, is generated in the _build/native/nativeCompile/_ directory of the project and ready for use.
```

2024-07-10 10:35 UTC, bhoran commented on fortune-demo/README.md
> +3. Run the application from the native executable:
```suggestion
3. Run the native executable:
```

2024-07-10 10:35 UTC, bhoran commented on fortune-demo/fortune-maven/pom.xml
> +        <maven.compiler.source>17</maven.compiler.source>
The README says to use JDK21.

2024-07-10 10:35 UTC, bhoran commented on fortune-demo/fortune-gradle/fortune/src/main/java/demo/Fortune.java
> +     private ArrayList<String> fortunes = new ArrayList<>();
This should be `final`

2024-07-10 10:35 UTC, bhoran commented on fortune-demo/fortune-maven/src/main/java/demo/Fortune.java
> +    private ArrayList<String> fortunes = new ArrayList<>();
```suggestion
    private final ArrayList<String> fortunes = new ArrayList<>();
```

2024-07-10 11:37 UTC, olyagpl commented on fortune-demo/fortune-gradle/fortune/src/main/java/demo/Fortune.java
> +     private ArrayList<String> fortunes = new ArrayList<>();
Suggestion applied

2024-07-10 11:50 UTC, bhoran approved these changes

2024-07-11 15:44 UTC, krisfoster approved these changes
All looks good.

2024-07-11 15:45 UTC, merged